###################
#' @title BEA to plastic sectors 
#' @Description Classifies consumption from the federal US EEIO model from 411 detailed
#' BEA sectors into plastic relevant sectors, summarizes the proportion of consumption in each
#' plastic relevant sector at the level of the 72 BEA summary codes which are used in the state-level model  
#' 
#' @param bea_to_plastic raw data input classifying each detailed BEA code into
#' one or more plastic relevant sectors with a corresponding proportion
#'
#' @return tidy data frame with columns bea_summary, plastic_sector, prop_consum
#' for all 72 summary sectors in the state model

preprocess_sectors <- function(bea_to_plastic) {

# Build the federal EPA EEIO model 
fed_io <- useeior::buildIOModel("USEEIOv2.0.1-411")

# Get sectors & add BEA summary code 
fed_bea_summary <- as.data.frame(fed_io[["crosswalk"]]) |> 
  dplyr::select(bea_summary=BEA_Summary, bea_detail=BEA_Detail) |> 
  distinct()

fed_bea <- as.data.frame(fed_io[["Commodities"]]) |> 
  mutate(bea_sector = str_extract(Category, pattern="^[^\\.:]+")) |> 
  dplyr::select(io_match=Code_Loc, bea_detail=Code, category=Category, bea_sector) |> 
  left_join(fed_bea_summary, by="bea_detail") |> 
  # crosswalk has the old 562000 only update summary code 
  mutate(bea_summary = ifelse(bea_sector == '56' & is.na(bea_summary), '562', bea_summary)) 

## Pull out the consumption data by sector & join match codes
fed_consumption <- as.data.frame(fed_io$q)
fed_consumption$io_match <- row.names(fed_consumption)
names(fed_consumption) <- c("us_consumption", "io_match")

fed_consumption <- fed_consumption |> 
  left_join(fed_bea, by = "io_match")

# Bea to plastic sector classification
## Raw data generated by Roland
plastic_props <- bea_to_plastic |> 
  dplyr::select(bea_detail, main_plastic_sector:secondary_sector_percent) |> 
  pivot_longer(cols = c("main_plastic_sector","secondary_plastic_sector"),
               names_to = "sector_level",
               values_to = "plastic_sector") |> 
  pivot_longer(cols = c("main_sector_percent","secondary_sector_percent"),
               names_to = "percent_level",
               values_to = "percent") |> 
  dplyr::mutate(sector_level = ifelse(str_detect(sector_level, "main"), "main", "secondary"),
                percent_level = ifelse(str_detect(percent_level, "main"), "main", "secondary")) |> 
  filter(sector_level == percent_level) |>
  dplyr::mutate(prop = percent / 100) |> 
  dplyr::select(bea_detail, plastic_sector, prop)


# Calculate proportion of each BEA sector to each plastic sector 
prop_plastic_consumption <- fed_consumption |> 
  left_join(plastic_props, by = "bea_detail", relationship = "one-to-many") |> 
  # Calculate consumption in each plastic category 
  dplyr::mutate(plastic_consumption = us_consumption * prop) |> 
  group_by(bea_summary) |> 
  mutate(bea_summary_total = sum(plastic_consumption)) |> 
  ungroup() |> 
  group_by(bea_summary, bea_summary_total, plastic_sector) |> 
  summarize(plastic_consumption = sum(plastic_consumption), .groups="drop") |> 
  mutate(prop = plastic_consumption / bea_summary_total) |> 
  filter(prop > 0) |> 
  dplyr::select(bea_summary, plastic_sector, prop_consum=prop)
  
return(prop_plastic_consumption)

}
